from django.conf.urls import patterns, url  # , include

urlpatterns = patterns('register.views',
                       url(r'^participant/create/$',
                           'participant', name='createParticipant'),
                       url(r'^participant/delete/(?P<id>\d+)/$',
                           'deleteParticipant', name='deleteParticipant'),
                       url(r'^participant/$',
                           'listParticipant', name='listParticipant'),
                       url(r'^participant/edit/(?P<id>\d+)/$',
                           'participant', name='editParticipant'),
                       url(r'^activate/participant/(.+?)/(.+?)/$',
                           'activateParticipant', name='activateParticipant'),
                       )

urlpatterns += patterns('register.views',
                        url(r'^team/create/$',
                            'createTeam', name='createTeam'),
                        url(r'^team/edit/(?P<id>\d+)/$',
                            'createTeam', name='editTeam'),
                        url(r'^team/$',
                            'listTeam', name='listTeam'),
                        url(r'^team/delete/(?P<id>\d+)/$',
                            'deleteTeam', name='deleteTeam'),
                        url(r'^team/users/(?P<id>\d+)/$',
                            'userTeam', name='userTeam'),
                        url(r'^team/list/league/(?P<id>\d+)/$',
                            'leagueTeams', name='leagueTeams'),
                        url(r'^team/list/league/final/(?P<id>\d+)/$',
                            'leagueTeamsFinal', name='leagueTeamsFinal'),
                        )
urlpatterns += patterns('register.views',
                        url(r'^$', 'login', name='login'),
                        url(r'^logout/$', 'logout', name='logout'),
                        url(r'^register/$', 'register', name='register'),
                        url(r'^profile/$', 'register', name='profile'),
                        url(r'^password/$', 'changePassword',
                            name='changePassword'),
                        url(r'^hint/$', 'forgetPassword',
                            name='forgetPassword'),
                        url(r'^redirect/$', 'redirect', name='redirect'),
                        url(r'^activate/email/(.+?)/(.+?)/$',
                            'activate', name='activate'),
                        )
urlpatterns += patterns('register.views',
                        url(r'^teampay/(?P<id>\d+)/$',
                            'teamPay', name='TeamPayment'),
                        url(r'^teampay/$',
                            'listTeamPay', name='listTeamPayment'),
                        url(r'^teampay/delete/(?P<id>\d+)/$',
                            'deleteTeamPay', name='deleteTeamPayment'),
                        )
urlpatterns += patterns('register.views',
                        url(r'^night/$',
                            'night', name='night'),
                        url(r'^night/pay/$',
                            'nightPay', name='nightPay'),
                        url(r'^night/delete/$',
                            'deleteNight', name='deleteNight'),
                        )

urlpatterns += patterns('register.views',
                        url(r'^finalUsers/$', 'listUsersCSV'),
                        url(r'^finalNightSuperviser/$',
                            'superviserNightFinal'),
                        )
