from django.conf.urls import patterns, url  # , include

urlpatterns = patterns('register.views',
                       url(r'^participant/create/$',
                           'participant', name='createParticipant'),
                       url(r'^participant/delete/(?P<id>\d+)/$',
                           'deleteParticipant', name='deleteParticipant'),
                       url(r'^participant/$',
                           'listParticipant', name='listParticipant'),
                       url(r'^participant/edit/(?P<id>\d+)/$',
                           'participant', name='editParticipant'),
                       url(r'^activate/participant/(.+?)/(.+?)/$',
                           'activateParticipant', name='activateParticipant'),
                       )
urlpatterns += patterns('register.views',
                        url(r'^team/create/$',
                            'createTeam', name='createTeam'),
                        url(r'^team/edit/(?P<id>\d+)/$',
                            'createTeam', name='editTeam'),
                        url(r'^team/$',
                            'listTeam', name='listTeam'),
                        url(r'^team/delete/(?P<id>\d+)/$',
                            'deleteTeam', name='deleteTeam'),
                        url(r'^team/users/(?P<id>\d+)/$',
                            'userTeam', name='userTeam'),
                        url(r'^team/list/league/(?P<id>\d+)/$',
                            'leagueTeams', name='leagueTeams'),
                        )
urlpatterns += patterns('register.views',
                        url(r'^$', 'login', name='login'),
                        url(r'^logout/$', 'logout', name='logout'),
                        url(r'^register/$', 'register', name='register'),
                        url(r'^profile/$', 'register', name='profile'),
                        url(r'^redirect/$', 'redirect', name='redirect'),
                        url(r'^activate/email/(.+?)/(.+?)/$',
                            'activate', name='activate'),
                        )
